import "./globals.scss";
import { DM_Sans, Inter } from "next/font/google";
import Header from "@/components/Header";

export const metadata = {
  title: "Banquee",
  description: "Generated by create next app",
};
const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "600"],
  variable: "--font-dmSans",
});
const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "600"],
  variable: "--font-inter",
});
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${dmSans.variable} ${inter.variable}`}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
